### ISSUE TITLE
Make program availablity form

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#109]
Allows admin user to set and view program availability times 

- gets and updates data from program availability endpoint 

- shows each program and beginning/ending hours for each day of the week (Sunday - Saturday)

**Comment by kyle-hauber** [comment]
@themightychris and/or @AilinLuca - below are some issues we're looking to address in our UX.  I've outlined the user problems as well as some potential solutions that we want to address

**User Problems:**

* As an Administrator, I need to be able to set and edit the opening hours for my program, so that the Front Desk Employees know when they should and should not check in participants.
    * Hours may change daily, so this is something administrators are changing frequently
* As a Front Desk Employee, I need to know the opening hours for each program, so that I only check-in participants during times that they can actually be seen.

**Context:**
Here's what they currently use to set and see the hours for a program:  https://docs.google.com/spreadsheets/d/1lWGxe8cbD7JfmhCxw-HlGsyvslDsMhQAEV3uGBskFls/edit?usp=sharing

Since we're working towards an MVP, we're trying to implement the simplest solution that we can deliver quickly (future iterations can improve upon this if feedback dictates).  For example - one approach could be to have a common component that displays the days/hours and we plug that component into a variety of places in the UI

**Potential Solutions:**
* have a separate page or modal that is only accessible by admins where they can edit the dates/hours of availability
* Have a button on the waitlist page that shows the hours
* show the hours in the program tabs on the waitlist page
* Show the hours on the check-in modal near the submit button (as a reminder for the FDE before they check them in)

I'll follow up with rough sketches of these ideas, but feel free to try other approaches too!

OUT OF SCOPE:
* Automatically closing the queue based on the hours of the program
* Automatically detecting the time and sending messages about who you can/can't check-in

cc: @mariekers
