### ISSUE TITLE
Update Queues in backend when changes are made on the front end Queues view

### ISSUE THREAD

**Issue by jkeary** [CodeForPhilly/prevention-point#163]
Right now if you make changes to the Queues table on the Queues view those changes are not updated in the database.  Changes that need to happen are the following

- [] changes in a row's status, notes, seen and urgency all have an update call made to the database
- [] update the Queue Store to add a hash for tracking changes made to the queues.  Add that hash variable to the ueEffect hook in the AllQueues component, so that when that hash is updated that will re-render the page with the new queues.

**Comment by mariekers** [comment]
@MikeyManoguerra or @mattusifer - mind checking this out?

**Comment by mattusifer** [comment]
@mariekers data the powers the queue (visits, visit_events) can be updated via the API. I think the path of least resistance right now is for the front-end should to hit those endpoints with any new data in order to update the underlying data in the correct places and then re-request the queue. For example, to update the notes to "new notes" on visit_id=x you'd send the following request:

```PATCH /api/visits/x {"notes": "new notes"}```

**Comment by jkeary** [comment]
Erm, @mariekers and @mattusifer, this isnt a backend ticket lol.  Sorry if that was confusing.  I created this ticket for a front end person to add the api calls from the Queue Table component

**Comment by hhummel** [comment]
Closed with merge of update-queues-163
