### ISSUE TITLE
dynamic queue store

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/prevention-point#289]
right now, program names are hardcoded into queue, and program_id is assumed. this is too rigid for a live application, if program name changes or id is different, will not work.

done: new piece of state: 'programs'
- array of programs,
- request made on sign in, persists for entire session. source of truth for program_id. 
- freeze queue can be validated / updated here.
@observable queues hard coded keys will need to become dynamic and based off of the new 'programs' state, as well as the computed queue stats.
This is a pretty big ticket that touches several parts of the application.  The person who takes this should get consensus from other devs that this outline makes sense.
it should also be held off until the front end directories  get  their planned restructuring

**Comment by ThrowsException** [comment]
I added a branch to start scoping out ideas for this. discuss here or hit me on the slack channel.

**Comment by MikeyManoguerra** [comment]
Throwing out an observation: `QueueStore.js` uses a variable called `queueIndex`. This is actually just the id of the program. the route is `api/programs/<program_id>/queue`. there is no queue table its an aggregation.

same thing in `queueEndpoints.js`. the parameter should be `programId`

**Comment by ThrowsException** [comment]
@MikeyManoguerra I did notice that theres really no "queue" is just all the participants in a particular program. I called this out on the slack channel that we probably want to take a look at how that data gets pulled because the current queue endpoint pulls from a bunch of tables duping a bunch of data and the endpoint is slow.

**Comment by MikeyManoguerra** [comment]
What it does is pull all visits with the current date (today) that are active on this program. 
Every time the front end visits the queue view, it makes a call to every program (10 in this case i think). so it just rebuilds the queue every time. I wrote the queue endpoint, and i am sure the query can be optimized because i think whats probably happening is in memory filtering. 

so, two places to optimize.

Also, i find the whole app pretty slow. i was hoping it has to do with the dev_env with parcel combined with docker db setup.

**Comment by ThrowsException** [comment]
It seems more to do with the network requests and the database queries. Just going to have to see where we can optimize some things on the backend or try to reduce the number/size of the requests.

**Comment by MikeyManoguerra** [comment]
Yes for example, if you go to  to `/participants` on the front end, the server should limit the number of results and allow for pagination, not just return every participant in the database.

**Comment by MikeyManoguerra** [comment]
and for the queue, once the session is loaded, we could only refresh the queue pages at a time interval, unless there is a submit event. 

then we could add a force refresh button if the user wants to refresh the queue without reloading the page

**Comment by MikeyManoguerra** [comment]
The updated permissions PR might help a little, also, bc it makes 2 round trips to db before allowing the view to execute currently

https://github.com/CodeForPhilly/prevention-point/blob/master/core/permissions.py
