### ISSUE TITLE
SEP form

### ISSUE THREAD

**Issue by sxgormley** [CodeForPhilly/prevention-point#406]
This form has two actions. one to search at `/api/participants`, and one to post at `/api/sep`
​
- create a local useState() that takes a number. this is participant id
- if participant id is blank, disable needles in/ out fields
- if participant id is present, disable participant info (name, maiden name, etc)
- datetime defaults to now
​
_SEARCH:_
here is a thread about the two action form. hopefully its enough reference: lets make the search the "lesser" action, if that is adecision to make.
​
https://github.com/formium/formik/issues/214
​
- if the query results length is 1, populate the name fields, and set the participant id useState
- otherwise, the user can populate the form from the participant list ( see seperate ticket #___ )
​
​
​
_POST:_
​
- set up validator object in `/validators/`. doesnt have to be exhaustive, but make sure things are present
- if the post is successful clear the form and the participant id state

**Comment by LizKalter** [comment]
@MikeyManoguerra @sxgormley Is the Figma board still an accurate representation of the SEP Search form? Site ID, SEP ID, last name, dob, mother's first name, needles in, needles out, exchanged for, and visit date. Fore each of these fields I need the corresponding parameter name to pass to api/participants and api/sep. I'm also not sure why Site ID is above the form title.

**Comment by MikeyManoguerra** [comment]
Yes, the figma board is accurate. the only thing missing is a 'clear' button. I should have mentioned this when I was formulating the ticket, can you add a clear button?

visit,
site,
created_at,
needles_in,
needles_out

Are the fields. Shoot and this was a good question because another thing you have to do before submitting to the api endpoint is to create a visit.

and to create a visit, you need a program and service. im not sure if we have the real program name in here. so just use `queueStore.queues[0].id` for the program, and `queueStore.queues[0].services[0].id` for the service, and leave a big `//TODO TEMP FIX ASAP` comment.


FYI we also do not want to create a front desk event for these sep visits, but ill write a specific ticket to fix this visit/ fde stuff and for now just hardcode it and let it create the front desk event for now.

**Comment by MikeyManoguerra** [comment]
@LizKalter ^^

**Comment by LizKalter** [comment]
@MikeyManoguerra Sorry, but the information here doesn't completely align with what I am seeing on the Figma board. If I'm looking at the wrong thing please let me know.

I am seeing 9 fields:

- Site ID (Why is this positioned above the form title? Does it have some special significance or behavior?)
- SEP ID
- Participant's Last Name
- Date of Birth
- Mother's First Name (Note that this is first name, not maiden name, so I'm not sure if this is correct.)

- Needles In (These 3 needle count related fields are dropdown menus. What are the values in these menus supposed to be?)
- Needles Out
- Exchanged For
- Visit Date

Can I get the names that these 9 fields correspond to on the backend? It might be helpful to have some sample data as well. For example, I have no idea what kind of input is expected for Site ID or SEP ID.

Where should the clear button be located and which fields does it affect?

Can you tell me which fields are required?

The original ticket description mentions "datetime defaults to now." What is this in reference to?

Thanks!

**Comment by sxgormley** [comment]
Hi @MikeyManoguerra ! What is the status of this ticket?
