### ISSUE TITLE
Check front end for hard coded values

### ISSUE THREAD

**Issue by MikeyManoguerra** [CodeForPhilly/prevention-point#447]
this one can be iceboxed for now but it should be done before putting in production. any values should rely on requests to back end for data

**Comment by MikeyManoguerra** [comment]
one potential solution is to add unchangeable slugs to program and service tables

**Comment by JackRyan1989** [comment]
So I actually have no idea what that means! Which is exciting. Maybe we could chat a bit more about that on Slack?

**Comment by MikeyManoguerra** [comment]
I specifically want to get these out of the component, the program and service ids here: 

https://github.com/CodeForPhilly/prevention-point/blob/24894c0bef8fc9b1105664936aee41645d6bbc5d/frontend/src/components/SepForm.js#L289

For a slug based solution:
- program and service tables each get a new field, slug
- slug can be provided or just the name provided normalized lowercase and spaces replaced with dashes or underscores.
- slug is required and uneditable
- need to a getqueryset for each of those views to query by slug
- useeffect in sep form component uses the slugs needed to get the needle exchange program/service ids,  and sets them as local state variables.

**Comment by JackRyan1989** [comment]
@MikeyManoguerra So for this particular case (SEP data), are the fields Urgency, Program and Service always going to be set to those particular values? If so, would it make sense to put the constants in the ParticipantStore rather than in the table itself? Also, by table field, do you mean values placed into the /constants index.js file? I would think we could then import those values into the ParticipantStore. Let me know if I'm totally off the mark here.

**Comment by MikeyManoguerra** [comment]
@JackRyan1989 sorry i missed these questions.
by tables and fields i was referring to db models
