### ISSUE TITLE
Search Results Page

### ISSUE THREAD

**Issue by kyle-hauber** [CodeForPhilly/prevention-point#83]
**User Story:**
As a front desk employee, I need to see a list of results that match my search so that I can find a participant in our system and not need to create a new record for people that have previously visited.

**Acceptance Criteria:**
- [x] Search Results page with columns of participant data
- [x] Should show columns for the following: UID, First Name, Last Name, DOB, Gender, and Race
- [x] Should have a column that includes a "plus button" that will send user to the participant details page (with participant detail filled in) to add them to the queue
- [x] Should have a button that allows the users to add a participant to the system if they aren't already in the results (i.e. if they don't appear in the results, they can still be added to the system/queue).  Will send user to the participant details page (without any details) to add new user. This button does not need to be functional for this story.

**Images:**
Search Results:  https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=0%3A1

No Results: https://www.figma.com/file/IikI37AjINeoyMxkL0emh4Er/Prevention-Point-Front-Desk?node-id=369%3A28190

**Comment by kyle-hauber** [comment]
@stacy - Are you still working on this?  Is there an issue/PR you can link? just trying to get a handle on current state.  Thanks!

**Comment by mariekers** [comment]
@Nkdiaz this'd be great

**Comment by jkeary** [comment]
I've created a separate branch off of master for this work called `Search_Results_Page_83`.  A few weeks back @hhummel and I had worked on connecting to the front end to the participants endpoints.  In the process we had created a component called `Participants`.  This component is on master/`Search_Results_Page_83` and is what we should use for this ticket for creating the search results page.  @hhummel, it doesn't appear to be working on master for me, did you merge your most recent stuff into master?  If not please do so I can pull this into this branch

**Comment by jkeary** [comment]
Right now I am working on the redirect from the `ParticipantSearch` component to this component.  @angelyoung24 has said she would work on the UI of this component.

**Comment by kyle-hauber** [comment]
@angelyoung24 - Can you please post an update here?  Let's use this format:
- What've you been working on for this story
- What're you working on next
- What blocker (if any) are you facing?

**Comment by angelyoung24** [comment]
Hey. Sorry I have been busy with other stuff and haven't gotten a chance to work on anything so I cannot really answer the first question since the last thing I worked on was getting the UI done.

The one blocker is testing. I have not idea how to test and I don't want to mess up what I already did until I am sure I know what I am doing.

**Comment by mariekers** [comment]
@jkeary @crsmyz - would either of you be interested in helping angel with some testing?

**Comment by jkeary** [comment]
Hi @angelyoung24, so 2 things:
1) I thought there were a few ui pieces left to this ticket that you needed to complete.  I dont know what they are, can you document those here?
2) As for automation testing here is the wiki doc that I created on testing: https://github.com/CodeForPhilly/prevention-point/wiki/Front-End-Automated-Testing.  If you still have questions let me know, but you can create some very simple tests without messing up things you have already done.

**Comment by mariekers** [comment]
@marcelkooi this ticket needs the testing that @jkeary mentions above

**Comment by mariekers** [comment]
@angelyoung24 have you pushed your work to a branch?

**Comment by jkeary** [comment]
- [ ] Need to add a footer element to the Participants List component for the Add New User section with icon.  https://material-ui.com/components/icons/#material-icons
- [ ] Add integration test to the button clicks.  See LoginForm.test

**Comment by jkeary** [comment]
@angelyoung24 and I circled up on this ticket last night and discussed whats next for it.  She was having trouble this week with her computer and had to reboot it, so not much has been done on it since then.  Here is what is left to do
[] add footer element to the Participant List component
[] add "add new user" icon / button the the right hand side of the footer element
[] add functionality that, on click of the add new user button will take you to the Participant Info view
[] add a Queue drop down window element to the component.  This element should appear on the button click of every row's "Add to queue" button.  
[] add functionality to that drop down.  The component on load should grab the list of queues from the QueueStore, this list should be displayed in the drop down.  On select of the a queue in the dropdown, the update queue endpoint should be hit to add that person to the queue
[] add functionality to each row in the table to go the participant's info page
[] add basic unit tests
[] add integration tests testing the button clicks

@angelyoung24 please comment in this ticket below which pieces you are working on.  If I were you I would take these in order of how I have listed them here.  I may have time this week to take some of these tasks and help you out, so please let me know which ones you are working on.

**Comment by angelyoung24** [comment]
@jkeary I am working on the footer and add new user button. I am running into a very small issue with styling the footer to look like the Figma. The issue is, I can't get the footer to turn that gray color. I don't know what file the styles for this page are coming from. I don't recognize it on the imports at the top of my page. I did manage to get to very close for now.

As of right now (11/9), I am running into an issue when I run `python manage.py migrate`. It says the table already exists. Since I don't feel comfortable dropping the table because backend is not something I feel comfortable with, I went ahead and run the app without migration and seeding. Due to this, there is no data on my end which means until I get this issue solved I cannot go any further right now. I will post this issue to the prevention point backend slack channel so I can move forward.

**Comment by jkeary** [comment]
Hi @angelyoung24, here's some docs on adding styles to material-ui components: https://material-ui.com/styles/basics/.  And as for the db issues you are having run the following commands in your prevention-point directory:
```pipenv shell
docker-compose down
docker volume prune```
Then you can re-up the docker container and do the migrations and seed, etc.  I'll update the readme.

**Comment by mariekers** [comment]
@angelyoung24 did these notes make sense?  Do you have any blockers here?  Anything we can help with?

**Comment by mariekers** [comment]
@angelyoung24 do you have any issues?  Can we help you with anything?

**Comment by angelyoung24** [comment]
@crsmyz has been added as of 12/3/19 @jkeary can you add him on.

**Comment by angelyoung24** [comment]
Nevermind @jkeary he was able to add himself on.
